import { Student } from "../../types/Student";

export const defaultStudents: Array<Student> = [
  {
    id: 0,
    name: "Student Test 0",
    homeUniversity: "Tuni",
    attendingUniversity: "Tuni",
    city: "Tre",
    cvLink: "",
    degreeLevelType: "bsc",
    notes: [],
    socialNetworkLinks: new Map(),
    studiesDescription: "",
    studiesField: "ITC",
    studiesType: "hard",
    whyGoodCreator: "reasons",
    whyJoinDemola: "good reasons",
    whyRole: "moti",
    applications: [],
  },
  {
    id: 1,
    name: "Student Test 1",
    homeUniversity: "Tuni",
    attendingUniversity: "Tuni",
    city: "Tre",
    cvLink: "",
    degreeLevelType: "bsc",
    notes: [],
    socialNetworkLinks: new Map(),
    studiesDescription: "",
    studiesField: "ITC",
    studiesType: "hard",
    whyGoodCreator: "reasons",
    whyJoinDemola: "good reasons",
    whyRole: "moti",
    applications: [],
  },
  {
    id: 2,
    name: "Student Test 2",
    homeUniversity: "Tuni",
    attendingUniversity: "Tuni",
    city: "Tre",
    cvLink: "",
    degreeLevelType: "bsc",
    notes: [],
    socialNetworkLinks: new Map(),
    studiesDescription: "",
    studiesField: "ITC",
    studiesType: "hard",
    whyGoodCreator: "reasons",
    whyJoinDemola: "good reasons",
    whyRole: "moti",
    applications: [],
  },
  {
    id: 3,
    name: "Student Test 3",
    homeUniversity: "Tuni",
    attendingUniversity: "Tuni",
    city: "Tre",
    cvLink: "",
    degreeLevelType: "bsc",
    notes: [],
    socialNetworkLinks: new Map(),
    studiesDescription: "",
    studiesField: "ITC",
    studiesType: "hard",
    whyGoodCreator: "reasons",
    whyJoinDemola: "good reasons",
    whyRole: "moti",
    applications: [],
  },
  {
    id: 4,
    name: "Student Test 4",
    homeUniversity: "Tuni",
    attendingUniversity: "Tuni",
    city: "Tre",
    cvLink: "",
    degreeLevelType: "bsc",
    notes: [],
    socialNetworkLinks: new Map(),
    studiesDescription: "",
    studiesField: "ITC",
    studiesType: "hard",
    whyGoodCreator: "reasons",
    whyJoinDemola: "good reasons",
    whyRole: "moti",
    applications: [],
  },
];
